### PR TITLE
[FIX] Status relaying on pipes

### LINKED ISSUE #68: fix: Wrong exit status when invalid command in left pipe
Fix the following test, which has an exit status of 0 instead of 1:
```json
{
    "name": "pipes - unknown left",
    "command": "unknowncommand | ls"
}
```
Note that the opposite (`ls | unknowncommand` works correctly right now).

### PR DESCRIPTION
**Pull request by Croos3r**
# Description

Please provide a detailed description of what was done in this PR.
Precise the issue that you are resolving.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to an issue
- [x] I have linked this PR to a milestone
- [x] I have linked this PR to a project
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

File: include/status.h [hunk 1]
```diff
@@ -0,0 +1,12 @@
+/*
```
Comment (EdenComp) [inline include/status.h]: par pitié change moi ça je veux bien split les headers mais pour une seule fonction non

**Review by EdenComp — CHANGES_REQUESTED** [review]

File: include/status.h (hunk 1 above)
Comment (Croos3r) [reply include/status.h]: Y'aura peut être d'autres truc à faire dedans et ça change pas grand chose en vrai

**Review by RezaRahemtola — APPROVED** [review]

**Review by EdenComp — APPROVED** [review]
